# Generated by Django 2.2.1 on 2019-05-20 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=20)),
                ('isDropdown', models.BooleanField(default=False)),
                ('url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=20)),
                ('url', models.TextField()),
                ('menuId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IntranetUser.Menu')),
            ],
        ),
    ]
