# Generated by Django 2.2.7 on 2019-11-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntranetUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='text',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='text',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='text',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='url',
            field=models.CharField(max_length=40),
        ),
    ]
