# Generated by Django 2.2.5 on 2020-03-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntranetUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='url',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
