# Generated by Django 2.2.5 on 2020-03-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntranetUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deptName', models.CharField(max_length=40)),
            ],
        ),
    ]
