# Generated by Django 2.2.1 on 2019-05-23 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IntranetUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='url',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=40)),
                ('hyperlink', models.TextField()),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IntranetUser.Category')),
            ],
        ),
    ]
