# Generated by Django 2.2.1 on 2019-05-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntranetUser', '0002_auto_20190523_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submenu',
            name='url',
            field=models.TextField(),
        ),
    ]
