# Generated by Django 2.2.5 on 2020-03-05 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IntranetUser', '0002_subcategory_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='content',
        ),
    ]
