# Generated by Django 2.2.5 on 2020-03-05 10:58

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IntranetUser', '0003_remove_subcategory_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submenu',
            name='content',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=None),
            preserve_default=False,
        ),
    ]
