# Generated by Django 2.2.5 on 2020-03-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntranetUser', '0003_auto_20200311_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submenu',
            name='text',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='url',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
