# Generated by Django 2.2.1 on 2019-05-23 14:17

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IntranetUser', '0004_auto_20190523_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
