# Generated by Django 2.2.5 on 2020-03-11 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IntranetUser', '0005_editor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editor',
            old_name='deptName',
            new_name='dept',
        ),
    ]
